//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaWebSıte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marka
    {
        public int MarkaId { get; set; }
        public string MarkaAdi { get; set; }
        public Nullable<int> kategoriId { get; set; }
    }
}
