//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaWebSıte.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class URUNLEREntities1 : DbContext
    {
        public URUNLEREntities1()
            : base("name=URUNLEREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<UrunlerTablosu> UrunlerTablosu { get; set; }
    
        public virtual ObjectResult<kategori_getir_Result> kategori_getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kategori_getir_Result>("kategori_getir");
        }
    
        public virtual int KategoriProcedure(string kategoriAdi)
        {
            var kategoriAdiParameter = kategoriAdi != null ?
                new ObjectParameter("kategoriAdi", kategoriAdi) :
                new ObjectParameter("kategoriAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KategoriProcedure", kategoriAdiParameter);
        }
    
        public virtual int MarkaProcedure(Nullable<int> kategoriId, string markaAdi)
        {
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("kategoriId", kategoriId) :
                new ObjectParameter("kategoriId", typeof(int));
    
            var markaAdiParameter = markaAdi != null ?
                new ObjectParameter("MarkaAdi", markaAdi) :
                new ObjectParameter("MarkaAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MarkaProcedure", kategoriIdParameter, markaAdiParameter);
        }
    
        public virtual int UrunProcedure(Nullable<int> urunId, Nullable<int> kategoriId, Nullable<int> markaID, Nullable<decimal> urunFiyati, string resim, string urunOzellik)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("UrunId", urunId) :
                new ObjectParameter("UrunId", typeof(int));
    
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("kategoriId", kategoriId) :
                new ObjectParameter("kategoriId", typeof(int));
    
            var markaIDParameter = markaID.HasValue ?
                new ObjectParameter("MarkaID", markaID) :
                new ObjectParameter("MarkaID", typeof(int));
    
            var urunFiyatiParameter = urunFiyati.HasValue ?
                new ObjectParameter("UrunFiyati", urunFiyati) :
                new ObjectParameter("UrunFiyati", typeof(decimal));
    
            var resimParameter = resim != null ?
                new ObjectParameter("Resim", resim) :
                new ObjectParameter("Resim", typeof(string));
    
            var urunOzellikParameter = urunOzellik != null ?
                new ObjectParameter("UrunOzellik", urunOzellik) :
                new ObjectParameter("UrunOzellik", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UrunProcedure", urunIdParameter, kategoriIdParameter, markaIDParameter, urunFiyatiParameter, resimParameter, urunOzellikParameter);
        }
    }
}
