//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UygulamaWebSıte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunlerTablosu
    {
        public int urunId { get; set; }
        public string Kategori { get; set; }
        public string Modeli { get; set; }
        public Nullable<int> Fiyati { get; set; }
        public string Resim { get; set; }
    }
}
